add docs for the 1.9 new features
formancehq/docs pull request #48
Opened 2023-03-06 14:37 UTC by jdupas22

- Added a part to the "metadata" Numscript chapter to explain how to set account metadata during a transaction
- Added a chapter to show how to use overdraft
- Added a chapter to show how to use an account balance as variable

2023-03-06 16:38 UTC, gfyrag approved these changes

2023-03-06 16:43 UTC, antoinegelloz commented on docs/ledger/numscript/metadata/index.mdx
> +set_account_meta(player:leslieknope, overdraft, false)
Accounts need "@" prefix in Numscript
```suggestion
set_account_meta(@player:leslieknope, overdraft, false)
```

2023-03-06 17:09 UTC, antoinegelloz requested changes

2023-03-06 17:09 UTC, antoinegelloz commented on docs/ledger/numscript/overdraft/index.mdx
> +The `kept` keyword allows you to specify a transaction that only moves a portion of the transaction amount. As a very basic example of the functionality, imagine that we need to send 15% of a 100 coi
Copy paste error ;)

2023-03-06 17:09 UTC, antoinegelloz commented on docs/ledger/numscript/overdraft/index.mdx
> +This is a great way to handle a simple case where an account need to go into negative. But sometimes we have business rules in place about negative accounts, for example the account player:leslieknop
```suggestion
This is a great way to handle a simple case where we need to allow overdraft on an account. But sometimes we have business rules in place about negative balance accounts, for example the account @player:leslieknope can only allow overdraft up to 5 COIN, because if a player goes into more than 5 COIN in debt, he will lose the game.
```

2023-03-06 17:09 UTC, antoinegelloz commented on docs/ledger/numscript/overdraft/index.mdx
> +  source = @player:leslieknope allowing overdraft up to [CONE 5]
```suggestion
  source = @player:leslieknope allowing overdraft up to [COIN 5]
```

2023-03-06 17:09 UTC, antoinegelloz commented on docs/ledger/numscript/overdraft/index.mdx
> +The user `annperkins` will receive 5 cones in total, even if leslieknope only has 3 cones available. This would put her account balance at a negative 2 cones.
```suggestion
The user `annperkins` will receive 5 COIN in total, even if `leslieknope` only has 3 COIN available. This would put the account balance at a negative 2 COIN. 
```

2023-03-06 17:09 UTC, antoinegelloz commented on docs/ledger/reference/numscript/sources.mdx
> +  destination = @world
This is not related to sources. I already documented this feature in the right page here: https://docs-git-dev-06032023-formance.vercel.app/ledger/reference/numscript/variables#monetary-type

2023-03-06 17:21 UTC, gfyrag commented on docs/ledger/reference/numscript/sources.mdx
> +  destination = @world
declared variables without vars key word works?
Also `send [$foo]` is ok? I don't think so.

2023-03-08 10:48 UTC, antoinegelloz commented on docs/ledger/numscript/metadata/index.mdx
> +Metadata is arbitrary data that you can attach to a transaction or an account. This data is typed, and can be a string or a number. You can retrieve (or even add to) this metadata later using the HTT
The types supported are actually all of them, i.e.:
`
set_tx_meta("aaa", @platform)
set_tx_meta("bbb", GEM)
set_tx_meta("ccc", 42)
set_tx_meta("ddd", "test")
set_tx_meta("eee", [COIN 30])
set_tx_meta("fff", 15%)
`

2023-03-08 10:53 UTC, antoinegelloz commented on docs/ledger/numscript/metadata/index.mdx
> +set_account_meta(@player:leslieknope, "overdraft", false)
Boolean is not a supported type, it needs to be quoted
```suggestion
set_account_meta(@player:leslieknope, "overdraft", "false")
```

2023-03-08 10:57 UTC, antoinegelloz commented on docs/ledger/numscript/overdraft/index.mdx
> +This is a great way to handle a simple case where we need to allow overdraft on an account. But sometimes we have business rules in place about negative balance accounts, for example the account @pla
To be consistent with the following paragraph
```suggestion
This is a great way to handle a simple case where we need to allow overdraft on an account. But sometimes we have business rules in place about negative balance accounts, for example the account @player:leslieknope can only allow overdraft up to 5 coins, because if a player goes into more than that in debt, he will lose the game.
```

2023-03-08 10:57 UTC, antoinegelloz commented on docs/ledger/numscript/overdraft/index.mdx
> +The user `annperkins` will receive 5 coins in total, even if leslieknope only has 3 coins available. This would put her account balance at a negative 2 cones.
```suggestion
The user `annperkins` will receive 5 coins in total, even if leslieknope only has 3 coins available. This would put her account balance at a negative 2 coins. 
```

2024-01-18 13:58 UTC, closed without merging